def build_markdown_report(records):
    """Membuat laporan dalam format markdown"""
    header = "# Rekap Nilai Mahasiswa\n\n"
    table_header = "| NIM | Nama | Hadir (%) | Nilai Akhir | Predikat |\n"
    table_separator = "|---|---|---:|---:|:---:|\n"
    
    table_rows = ""
    for record in records:
        row = (f"| {record['nim']} | {record['nama']} | {record['hadir_persen']} | "
               f"{record['nilai_akhir']:.2f} | {record['predikat']} |\n")
        table_rows += row
    
    footer = "\n*Generated by student_performance_tracker*"
    
    return header + table_header + table_separator + table_rows + footer

def save_text(path, content):
    """Menyimpan konten ke file"""
    with open(path, 'w', encoding='utf-8') as file:
        file.write(content)